name = "genom-v4"name = "genom-v4-api"
main = "functions/_worker.js"
compatibility_date = "2025-04-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "genom-v4-db"
database_id = ""

[[env.staging]]
[[env.staging.d1_databases]]
binding = "DB"
database_name = "genom-v4-db-staging"
database_id = ""

[env.production]
